---
name: "Manual terraform plan and apply"

on:
  workflow_dispatch:
    inputs:
      plan_or_apply:
        description: "Select if you want to do"
        type: choice
        required: true
        options:
          - "plan"
          - "apply"

jobs:
  terraform-manual-apply:
    runs-on: ubuntu-latest
    env:
      TF_ACTION_WORKING_DIR: .

    steps:

    - name: "Checkout the repository"
      uses: actions/checkout@v3

    - name: "Setup Terraform"
      uses: hashicorp/setup-terraform@v2

    - name: "Run terraform init"
      id: init
      run: "terraform init -no-color"
    
    - name: "Run terraform validate"
      id: validate
      run: "terraform validate -no-color"

    - name: "Run terraform plan"
      id: plan
      run: "terraform plan -no-color -input=false -out tfplan"

    - name: "Run terraform apply"
      if: ${{ inputs.plan_or_apply == 'apply' }}
      run: "terraform apply -no-color -auto-approve -input=false tfplan"
